[tool.poetry]
name = "курсовой проект 5"
version = "0.1.0"
description = ""
authors = ["ferrum76 <daniil.zheleznyakov.2000@gmail.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"